# DB config
spring.datasource.url=jdbc:mysql://localhost:3306/rec_platform
spring.datasource.username=root
spring.datasource.password=DAC@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Secret Key (later used in service)
jwt.secret=cdacproject

# spring.mail.username=parthpidurkar.cdac@gmail.com
# spring.mail.password=tpbb rgnj gfgg hofq
spring.mail.username=flashdaniel2012@gmail.com
spring.mail.password=fmnd zaeh nipx baur

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true